// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mimix_obj.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addObj = `-- name: AddObj :one
INSERT INTO mimix_obj (obj, obj_type, promote_date, obj_ver, lib, lib_id, mimix_status, developer)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, obj, obj_type, promote_date, obj_ver, lib, lib_id, mimix_status, developer
`

type AddObjParams struct {
	Obj         string
	ObjType     string
	PromoteDate sql.NullTime
	ObjVer      string
	Lib         string
	LibID       uuid.UUID
	MimixStatus MimixStatus
	Developer   string
}

type AddObjRow struct {
	ID          uuid.UUID
	Obj         string
	ObjType     string
	PromoteDate sql.NullTime
	ObjVer      string
	Lib         string
	LibID       uuid.UUID
	MimixStatus MimixStatus
	Developer   string
}

func (q *Queries) AddObj(ctx context.Context, arg AddObjParams) (AddObjRow, error) {
	row := q.db.QueryRowContext(ctx, addObj,
		arg.Obj,
		arg.ObjType,
		arg.PromoteDate,
		arg.ObjVer,
		arg.Lib,
		arg.LibID,
		arg.MimixStatus,
		arg.Developer,
	)
	var i AddObjRow
	err := row.Scan(
		&i.ID,
		&i.Obj,
		&i.ObjType,
		&i.PromoteDate,
		&i.ObjVer,
		&i.Lib,
		&i.LibID,
		&i.MimixStatus,
		&i.Developer,
	)
	return i, err
}

const addObjToObjReq = `-- name: AddObjToObjReq :exec
INSERT INTO mimix_obj_req (
    obj_name,
    requester,
    req_status,
    created_at,
    updated_at,
    lib,
    obj_ver,
    obj_type,
    promote_date,
    developer,
    source_obj_id
)
SELECT
    o.obj,
    $2,
    $3,
    NOW(),
    NOW(),
    o.lib,
    o.obj_ver,
    o.obj_type,
    o.promote_date,
    o.developer,
    o.id          -- source obj id
FROM mimix_obj AS o
WHERE o.id = $1
`

type AddObjToObjReqParams struct {
	ID        uuid.UUID
	Requester string
	ReqStatus ReqStatus
}

func (q *Queries) AddObjToObjReq(ctx context.Context, arg AddObjToObjReqParams) error {
	_, err := q.db.ExecContext(ctx, addObjToObjReq, arg.ID, arg.Requester, arg.ReqStatus)
	return err
}

const completeObjMimixStatus = `-- name: CompleteObjMimixStatus :exec
UPDATE mimix_obj
SET mimix_status = 'done'
WHERE id = $1
`

func (q *Queries) CompleteObjMimixStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, completeObjMimixStatus, id)
	return err
}

const getMimixStatusByID = `-- name: GetMimixStatusByID :one
SELECT mimix_status
FROM mimix_obj
WHERE id = $1
`

func (q *Queries) GetMimixStatusByID(ctx context.Context, id uuid.UUID) (MimixStatus, error) {
	row := q.db.QueryRowContext(ctx, getMimixStatusByID, id)
	var mimix_status MimixStatus
	err := row.Scan(&mimix_status)
	return mimix_status, err
}

const getObjByID = `-- name: GetObjByID :one
SELECT id, obj, obj_type, promote_date, lib, lib_id, obj_ver, mimix_status, developer, keterangan
FROM mimix_obj
WHERE id = $1
`

func (q *Queries) GetObjByID(ctx context.Context, id uuid.UUID) (MimixObj, error) {
	row := q.db.QueryRowContext(ctx, getObjByID, id)
	var i MimixObj
	err := row.Scan(
		&i.ID,
		&i.Obj,
		&i.ObjType,
		&i.PromoteDate,
		&i.Lib,
		&i.LibID,
		&i.ObjVer,
		&i.MimixStatus,
		&i.Developer,
		&i.Keterangan,
	)
	return i, err
}

const removeObjByID = `-- name: RemoveObjByID :exec
DELETE FROM mimix_obj
WHERE id = $1
`

func (q *Queries) RemoveObjByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeObjByID, id)
	return err
}

const searchMimixObj = `-- name: SearchMimixObj :many
SELECT id, obj, obj_type, promote_date, lib, lib_id, obj_ver, mimix_status, developer, keterangan
FROM mimix_obj
WHERE
    obj ILIKE '%' || $1 || '%'
 OR lib ILIKE '%' || $1 || '%'
 OR developer ILIKE '%' || $1 || '%'
`

func (q *Queries) SearchMimixObj(ctx context.Context, dollar_1 sql.NullString) ([]MimixObj, error) {
	rows, err := q.db.QueryContext(ctx, searchMimixObj, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MimixObj
	for rows.Next() {
		var i MimixObj
		if err := rows.Scan(
			&i.ID,
			&i.Obj,
			&i.ObjType,
			&i.PromoteDate,
			&i.Lib,
			&i.LibID,
			&i.ObjVer,
			&i.MimixStatus,
			&i.Developer,
			&i.Keterangan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMimixStatus = `-- name: UpdateMimixStatus :exec
UPDATE mimix_obj
SET mimix_status = $2
WHERE id = $1
`

type UpdateMimixStatusParams struct {
	ID          uuid.UUID
	MimixStatus MimixStatus
}

func (q *Queries) UpdateMimixStatus(ctx context.Context, arg UpdateMimixStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMimixStatus, arg.ID, arg.MimixStatus)
	return err
}

const updateObjInfo = `-- name: UpdateObjInfo :one
UPDATE mimix_obj
SET
    obj           = $2,
    lib           = $3,
    obj_type      = $4,
    obj_ver       = $5,
    promote_date  = $6,
    mimix_status  = $7,
    developer     = $8,
    keterangan    = $9
WHERE id = $1
RETURNING id, obj, obj_type, promote_date, lib, lib_id, obj_ver, mimix_status, developer, keterangan
`

type UpdateObjInfoParams struct {
	ID          uuid.UUID
	Obj         string
	Lib         string
	ObjType     string
	ObjVer      string
	PromoteDate sql.NullTime
	MimixStatus MimixStatus
	Developer   string
	Keterangan  sql.NullString
}

func (q *Queries) UpdateObjInfo(ctx context.Context, arg UpdateObjInfoParams) (MimixObj, error) {
	row := q.db.QueryRowContext(ctx, updateObjInfo,
		arg.ID,
		arg.Obj,
		arg.Lib,
		arg.ObjType,
		arg.ObjVer,
		arg.PromoteDate,
		arg.MimixStatus,
		arg.Developer,
		arg.Keterangan,
	)
	var i MimixObj
	err := row.Scan(
		&i.ID,
		&i.Obj,
		&i.ObjType,
		&i.PromoteDate,
		&i.Lib,
		&i.LibID,
		&i.ObjVer,
		&i.MimixStatus,
		&i.Developer,
		&i.Keterangan,
	)
	return i, err
}

const updateObjStatus = `-- name: UpdateObjStatus :exec
UPDATE mimix_obj
SET mimix_status = $2
WHERE obj = $1
RETURNING obj, mimix_status
`

type UpdateObjStatusParams struct {
	Obj         string
	MimixStatus MimixStatus
}

func (q *Queries) UpdateObjStatus(ctx context.Context, arg UpdateObjStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateObjStatus, arg.Obj, arg.MimixStatus)
	return err
}
