// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mimix_obj_req.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeMimixObjReq = `-- name: CompleteMimixObjReq :exec
UPDATE mimix_obj_req
SET req_status = 'completed', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteMimixObjReq(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, completeMimixObjReq, id)
	return err
}

const createMimixObjReq = `-- name: CreateMimixObjReq :one
INSERT INTO mimix_obj_req (
    obj_name,
    requester,
    req_status,
    lib,
    obj_ver,
    obj_type,
    promote_date
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, obj_name, requester, req_status, lib, obj_ver, obj_type, promote_date, created_at, updated_at
`

type CreateMimixObjReqParams struct {
	ObjName     string
	Requester   string
	ReqStatus   string
	Lib         string
	ObjVer      string
	ObjType     string
	PromoteDate time.Time
}

type CreateMimixObjReqRow struct {
	ID          uuid.UUID
	ObjName     string
	Requester   string
	ReqStatus   string
	Lib         string
	ObjVer      string
	ObjType     string
	PromoteDate time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateMimixObjReq(ctx context.Context, arg CreateMimixObjReqParams) (CreateMimixObjReqRow, error) {
	row := q.db.QueryRowContext(ctx, createMimixObjReq,
		arg.ObjName,
		arg.Requester,
		arg.ReqStatus,
		arg.Lib,
		arg.ObjVer,
		arg.ObjType,
		arg.PromoteDate,
	)
	var i CreateMimixObjReqRow
	err := row.Scan(
		&i.ID,
		&i.ObjName,
		&i.Requester,
		&i.ReqStatus,
		&i.Lib,
		&i.ObjVer,
		&i.ObjType,
		&i.PromoteDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMimixObjReq = `-- name: GetMimixObjReq :many
SELECT id, obj_name, requester, req_status, created_at, updated_at, lib, obj_ver, obj_type, promote_date, developer, promote_status, source_obj_id
FROM mimix_obj_req
`

func (q *Queries) GetMimixObjReq(ctx context.Context) ([]MimixObjReq, error) {
	rows, err := q.db.QueryContext(ctx, getMimixObjReq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MimixObjReq
	for rows.Next() {
		var i MimixObjReq
		if err := rows.Scan(
			&i.ID,
			&i.ObjName,
			&i.Requester,
			&i.ReqStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Lib,
			&i.ObjVer,
			&i.ObjType,
			&i.PromoteDate,
			&i.Developer,
			&i.PromoteStatus,
			&i.SourceObjID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMimixObjReqByID = `-- name: GetMimixObjReqByID :one
SELECT id, obj_name, requester, req_status, created_at, updated_at, lib, obj_ver, obj_type, promote_date, developer, promote_status, source_obj_id
FROM mimix_obj_req
WHERE id = $1
`

func (q *Queries) GetMimixObjReqByID(ctx context.Context, id uuid.UUID) (MimixObjReq, error) {
	row := q.db.QueryRowContext(ctx, getMimixObjReqByID, id)
	var i MimixObjReq
	err := row.Scan(
		&i.ID,
		&i.ObjName,
		&i.Requester,
		&i.ReqStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lib,
		&i.ObjVer,
		&i.ObjType,
		&i.PromoteDate,
		&i.Developer,
		&i.PromoteStatus,
		&i.SourceObjID,
	)
	return i, err
}

const getMimixObjReqByRequester = `-- name: GetMimixObjReqByRequester :many
SELECT id, obj_name, requester, req_status, created_at, updated_at, lib, obj_ver, obj_type, promote_date, developer, promote_status, source_obj_id
FROM mimix_obj_req
WHERE requester = $1
`

func (q *Queries) GetMimixObjReqByRequester(ctx context.Context, requester string) ([]MimixObjReq, error) {
	rows, err := q.db.QueryContext(ctx, getMimixObjReqByRequester, requester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MimixObjReq
	for rows.Next() {
		var i MimixObjReq
		if err := rows.Scan(
			&i.ID,
			&i.ObjName,
			&i.Requester,
			&i.ReqStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Lib,
			&i.ObjVer,
			&i.ObjType,
			&i.PromoteDate,
			&i.Developer,
			&i.PromoteStatus,
			&i.SourceObjID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMimixObjReq = `-- name: RemoveMimixObjReq :exec
DELETE FROM mimix_obj_req
WHERE id = $1
RETURNING obj_name
`

func (q *Queries) RemoveMimixObjReq(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeMimixObjReq, id)
	return err
}

const updateMimixObjReqStatus = `-- name: UpdateMimixObjReqStatus :exec
UPDATE mimix_obj_req
SET req_status = $1
WHERE id = $2
`

type UpdateMimixObjReqStatusParams struct {
	ReqStatus string
	ID        uuid.UUID
}

func (q *Queries) UpdateMimixObjReqStatus(ctx context.Context, arg UpdateMimixObjReqStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMimixObjReqStatus, arg.ReqStatus, arg.ID)
	return err
}
