// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mimix_obj.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addObj = `-- name: AddObj :one
INSERT INTO mimix_obj (obj, obj_type, promote_date, obj_ver, lib, mimix_status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, obj, obj_type, promote_date, obj_ver, lib, mimix_status
`

type AddObjParams struct {
	Obj         string
	ObjType     string
	PromoteDate time.Time
	ObjVer      string
	Lib         string
	MimixStatus string
}

type AddObjRow struct {
	ID          uuid.UUID
	Obj         string
	ObjType     string
	PromoteDate time.Time
	ObjVer      string
	Lib         string
	MimixStatus string
}

func (q *Queries) AddObj(ctx context.Context, arg AddObjParams) (AddObjRow, error) {
	row := q.db.QueryRowContext(ctx, addObj,
		arg.Obj,
		arg.ObjType,
		arg.PromoteDate,
		arg.ObjVer,
		arg.Lib,
		arg.MimixStatus,
	)
	var i AddObjRow
	err := row.Scan(
		&i.ID,
		&i.Obj,
		&i.ObjType,
		&i.PromoteDate,
		&i.ObjVer,
		&i.Lib,
		&i.MimixStatus,
	)
	return i, err
}

const removeObj = `-- name: RemoveObj :exec
DELETE FROM mimix_obj
WHERE obj = $1
`

func (q *Queries) RemoveObj(ctx context.Context, obj string) error {
	_, err := q.db.ExecContext(ctx, removeObj, obj)
	return err
}

const updateObjStatus = `-- name: UpdateObjStatus :exec
UPDATE mimix_obj
SET mimix_status = $2
WHERE obj = $1
`

type UpdateObjStatusParams struct {
	Obj         string
	MimixStatus string
}

func (q *Queries) UpdateObjStatus(ctx context.Context, arg UpdateObjStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateObjStatus, arg.Obj, arg.MimixStatus)
	return err
}
