// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mimix_lib.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMimixLib = `-- name: CreateMimixLib :one
INSERT INTO mimix_lib (lib)
VALUES ($1)
RETURNING id, lib
`

func (q *Queries) CreateMimixLib(ctx context.Context, lib string) (MimixLib, error) {
	row := q.db.QueryRowContext(ctx, createMimixLib, lib)
	var i MimixLib
	err := row.Scan(&i.ID, &i.Lib)
	return i, err
}

const getMimixLibByName = `-- name: GetMimixLibByName :one
SELECT id, lib
FROM mimix_lib
WHERE lib = $1
`

func (q *Queries) GetMimixLibByName(ctx context.Context, lib string) (MimixLib, error) {
	row := q.db.QueryRowContext(ctx, getMimixLibByName, lib)
	var i MimixLib
	err := row.Scan(&i.ID, &i.Lib)
	return i, err
}

const updateObjLibID = `-- name: UpdateObjLibID :exec
UPDATE mimix_obj
SET lib_id = $2
WHERE id = $1
`

type UpdateObjLibIDParams struct {
	ID    uuid.UUID
	LibID uuid.UUID
}

func (q *Queries) UpdateObjLibID(ctx context.Context, arg UpdateObjLibIDParams) error {
	_, err := q.db.ExecContext(ctx, updateObjLibID, arg.ID, arg.LibID)
	return err
}
