// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mimix_lib.sql

package database

import (
	"context"
)

const addLib = `-- name: AddLib :one
INSERT INTO mimix_lib (lib)
VALUES ($1)
RETURNING id, lib
`

func (q *Queries) AddLib(ctx context.Context, lib string) (MimixLib, error) {
	row := q.db.QueryRowContext(ctx, addLib, lib)
	var i MimixLib
	err := row.Scan(&i.ID, &i.Lib)
	return i, err
}

const deleteLib = `-- name: DeleteLib :exec
DELETE FROM mimix_lib
WHERE lib = $1
`

func (q *Queries) DeleteLib(ctx context.Context, lib string) error {
	_, err := q.db.ExecContext(ctx, deleteLib, lib)
	return err
}
