// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type MimixLib struct {
	ID  uuid.UUID
	Lib string
}

type MimixObj struct {
	ID          uuid.UUID
	Obj         string
	ObjType     string
	PromoteDate time.Time
	Lib         string
	LibID       uuid.UUID
	ObjVer      string
	MimixStatus string
}

type User struct {
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Pass      string
}
