// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type MimixStatus string

const (
	MimixStatusUnset            MimixStatus = "unset"
	MimixStatusDone             MimixStatus = "done"
	MimixStatusDaftarkan        MimixStatus = "daftarkan"
	MimixStatusTidakperludaftar MimixStatus = "tidak perlu daftar"
	MimixStatusOnprogress       MimixStatus = "on progress"
)

func (e *MimixStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MimixStatus(s)
	case string:
		*e = MimixStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MimixStatus: %T", src)
	}
	return nil
}

type NullMimixStatus struct {
	MimixStatus MimixStatus
	Valid       bool // Valid is true if MimixStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMimixStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MimixStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MimixStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMimixStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MimixStatus), nil
}

type PromoteStatus string

const (
	PromoteStatusInProgress PromoteStatus = "in_progress"
	PromoteStatusDeployed   PromoteStatus = "deployed"
)

func (e *PromoteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoteStatus(s)
	case string:
		*e = PromoteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoteStatus: %T", src)
	}
	return nil
}

type NullPromoteStatus struct {
	PromoteStatus PromoteStatus
	Valid         bool // Valid is true if PromoteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PromoteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoteStatus), nil
}

type ReqStatus string

const (
	ReqStatusPending   ReqStatus = "pending"
	ReqStatusCompleted ReqStatus = "completed"
)

func (e *ReqStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReqStatus(s)
	case string:
		*e = ReqStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReqStatus: %T", src)
	}
	return nil
}

type NullReqStatus struct {
	ReqStatus ReqStatus
	Valid     bool // Valid is true if ReqStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReqStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReqStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReqStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReqStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReqStatus), nil
}

type UserJob string

const (
	UserJobCmt  UserJob = "cmt"
	UserJobDev  UserJob = "dev"
	UserJobDc   UserJob = "dc"
	UserJobUser UserJob = "user"
)

func (e *UserJob) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserJob(s)
	case string:
		*e = UserJob(s)
	default:
		return fmt.Errorf("unsupported scan type for UserJob: %T", src)
	}
	return nil
}

type NullUserJob struct {
	UserJob UserJob
	Valid   bool // Valid is true if UserJob is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserJob) Scan(value interface{}) error {
	if value == nil {
		ns.UserJob, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserJob.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserJob) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserJob), nil
}

type MimixLib struct {
	ID  uuid.UUID
	Lib string
}

type MimixObj struct {
	ID          uuid.UUID
	Obj         string
	ObjType     string
	PromoteDate sql.NullTime
	Lib         string
	LibID       uuid.UUID
	ObjVer      string
	MimixStatus MimixStatus
	Developer   string
	Keterangan  sql.NullString
	UpdatedAt   time.Time
}

type MimixObjReq struct {
	ID            uuid.UUID
	ObjName       string
	Requester     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Lib           string
	ObjVer        string
	ObjType       string
	PromoteDate   time.Time
	Developer     sql.NullString
	PromoteStatus NullPromoteStatus
	SourceObjID   uuid.NullUUID
	ReqStatus     ReqStatus
}

type User struct {
	ID             uuid.UUID
	Username       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
	Job            UserJob
}
