// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password, job)
VALUES ($1, $2, $3)
RETURNING username, job, created_at, updated_at
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
	Job            UserJob
}

type CreateUserRow struct {
	Username  string
	Job       UserJob
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.HashedPassword, arg.Job)
	var i CreateUserRow
	err := row.Scan(
		&i.Username,
		&i.Job,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, job, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        uuid.UUID
	Username  string
	Job       UserJob
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Job,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, job, hashed_password, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID             uuid.UUID
	Username       string
	Job            UserJob
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Job,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userLogin = `-- name: UserLogin :one
SELECT id, username, created_at, updated_at, hashed_password, job
FROM users
WHERE username = $1
`

func (q *Queries) UserLogin(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, userLogin, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.Job,
	)
	return i, err
}
