// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, pass)
VALUES ($1, $2)
RETURNING email, created_at, updated_at
`

type CreateUserParams struct {
	Email string
	Pass  string
}

type CreateUserRow struct {
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Pass)
	var i CreateUserRow
	err := row.Scan(&i.Email, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const userLogin = `-- name: UserLogin :one
SELECT email, created_at, updated_at, pass
FROM users
WHERE email = $1
`

func (q *Queries) UserLogin(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userLogin, email)
	var i User
	err := row.Scan(
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Pass,
	)
	return i, err
}
